name: line_it_up
description: "A Ecommerce App."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  formz: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
 
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter-18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter-18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter-18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter-18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter-18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter-24pt-Bold.ttf
          weight: 700
  